export const mnemonicDb: Record<string, string[]> = {
  "00":["snooze"],
  "01": ["sat", "suit", "seed"],
  "02": ["sun", "swan", "snow"],
  "03": ["sum", "swim", "smile"],
  "04": ["sir"],
  "05": [ "seal", "sale"],
  "06": ["switch", "sushi"],
  "07": ["sock", "sack", "sick"],
  "08": ["safe", "sofa", "surf"],
  "09": ["soap", "soup"],
  "10": ["toes", "dice", "dose"],
  "11": ["toad"],
  "12": ["tune", "twin"],
  "13": ["team", "dome", "time"],
  "14": ["tire", "tear", "tower"],
  "15": ["towel", "tile", "tale"],
  "16": ["touch", "dash", "dish"],
  "17": ["duck", "deck", "dog"],
  "18": ["dive", "dove"],
  "19": ["tape", "top", "tap"],
  "20": ["nose", "news"],

  "21": ["net", "knot", "nut"],
  "22": ["nun", "neon", "nine"],
  "23": ["name", "gnome", "numb"],
  "24": ["noir"],
  "25": ["nail"],
  "26": ["nudge", "nacho"],
  "27": ["neck", "nuke"],
  "28": ["knife"],
  "29": ["nap", "knob"],
  "30": ["mouse", "maze"],
  "31": ["mat", "mad", "mud"],
  "32": ["moon", "man", "mine"],
  "33": ["mum", "mummy", "mime"],
  "34": ["hammer"],
  "35": ["meal"],
  "36": ["mash", "mush"],
  "37": ["mug"],
  "38": ["move", "mafia"],
  "39": ["map", "mope"],
  "40": ["rose", "race", "rice"],
  "41": ["rat", "road", "rode"],
  "42": ["rain", "run"],
  "43": ["rum", "rhyme"],
  "44": ["rare", "roar"],
  "45": ["roll", "rule"],
  "46": ["rash"],
  "47": ["rock"],
  "48": ["roof"],
  "49": ["rap", "rope", "rip"],
  "50": ["lose"],
  "51": ["lid"],
  "52": ["line", "lion"],
  "53": ["lime", "lamb"],
  "54": ["lure", "lair"],
  "55": ["lily"],
  "56": ["lush", "ledge"],
  "57": ["luck", "lick"],
  "58": ["leaf", "lava"],
  "59": ["lip", "loop", "lap"],
  "60": ["chess", "juice"],
  "61": ["jet"],
  "62": ["chain", "shine"],
  "63": ["jam"],
  "64": ["chair", "shower", "jar"],
  "65": ["jail", "chill"],
  "66": ["judge", "shush"],
  "67": ["chalk", "jack", "jug"],
  "68": ["chef"],
  "69": ["ship", "jeep"],
  "70": ["case", "keys"],
  "71": ["cat", "cut"],
  "72": ["can", "coin"],
  "73": ["comb", "gum"],
  "74": ["car", "care"],
  "75": ["coal", "call", "kale"],
  "76": ["cash", "cage"],
  "77": ["cog", "coke", "cake"],
  "78": ["cough", "cave", "coffee"],
  "79": ["cap"],
  "80": ["face"],
  "81": ["foot"],
  "82": ["fun", "phone", "fan"],
  "83": ["foam", "fume"],
  "84": ["fire", "fur"],
  "85": ["fall", "foil"],
  "86": ["fish"],
  "87": ["fake", "fog"],
  "88": ["five"],
  "89": ["fav"],
  "90": ["buzz", "peace"],
  "91": ["bat", "bed", "bad"],
  "92": ["bun", "ban", "bone"],
  "93": ["bomb"],
  "94": ["bear", "bar"],
  "95": ["bell", "ball"],
  "96": ["beach", "bush"],
  "97": ["pack", "poke"],
  "98": ["puff"],
  "99": ["pope", "puppy"],
  "0": ["saw", "sew", "so"],
  "1": ["tie", "toe", "tea"],
  "2": ["no", "knee", "nay"],
  "3": ["me", "may", "my"],
  "4": ["raw", "row"],
  "5": ["lay", "low", "law"],
  "6": ["jay", "jaw", "joe"],
  "7": ["key", "cow"],
  "8": ["ivy", "foe"],
  "9": ["pie", "paw"],
};
